userId = 'TJ0224'
authToken = 'enctoken YOth4LTsIZXDDUQ06mq7X4HfRtPCppV0XaO/eIUYjK0eUS/tan+f4lhIlaGeI9rK1lztKO/YC/adX10qBd1AH6yN/Bwr4YAd3Jqsv0epaJI4qLFyCbAg9Q=='

auth_key = ''
regular = 'regular'
nse = 'NSE'
bse = 'BSE'
buy = 'BUY'
sell = 'SELL'
limit = 'LIMIT'
market = 'MARKET'
cnc = 'CNC'
day = 'DAY'

place_order_api = 'https://kite.zerodha.com/oms/orders/regular'
minute_market_data_api = 'https://kite.zerodha.com/oms/instruments/historical/#token/minute'