USER_ID = 'TJ0224'
AUTH_TOKEN = 'enctoken 042xh3hL+74d2fyW9JzrMh8tk95Zb/MfnfpZfDR4B9BKvOshSsMfB5Zu8sFnCgPqbrq95uFHzW7SrSsezj2dIDWekgvbj6JcU3Hoc7UULaFyCl+FT3rmZA=='

REGULAR = 'regular'
NSE = 'NSE'
BSE = 'BSE'
BUY = 'BUY'
SELL = 'SELL'
LIMIT = 'LIMIT'
MARKET = 'MARKET'
CNC = 'CNC'
MIS = 'MIS'
DAY = 'DAY'
POSITION_CLOSE_TIME = '15:15'
INSTRUMENT_TOKEN_CSV_PATH = '/Users/ajith/Desktop/instrument_tokens.csv'

PLACE_ORDER_API = 'https://kite.zerodha.com/oms/orders/regular'
MINUTE_MARKET_DATA_API = 'https://kite.zerodha.com/oms/instruments/historical/#token/minute'
CASH_MARGIN_API = 'https://kite.zerodha.com/oms/user/margins'
POSITION_BOOK_API = 'https://kite.zerodha.com/oms/portfolio/positions'
INSTRUMENT_TOKEN = "https://api.kite.trade/instruments"
